/**
 * Estimation data-access service (server-only).
 *
 * Prisma-backed replacement for the estimation methods of the legacy PouchDB
 * `ApiService` (`src/api/index.ts`): `createNewEstimation`, `updateEstimation`
 * (including its "set every other estimation inactive" reduce — the
 * single-active-estimation invariant), `deleteEstimation`, and
 * `importEstimations` (the CSV bulk merge).
 *
 * The legacy `updateEstimation` conflated "activate this estimation" with
 * "rename/patch this estimation" inside one CouchDB document mutation. Here they
 * are split into cohesive operations:
 * - {@link updateEstimation} patches scalar fields (name/description/isEnded).
 * - {@link activateEstimation} enforces the single-active invariant atomically.
 *
 * All writes go through the shared Prisma client, so the `pg_notify` triggers in
 * `@scrum-poker/db` fire automatically and feed the SSE layer (issue #12).
 */
import "server-only";

import { prisma, toEstimation } from "@scrum-poker/db";
import type { Estimation } from "@scrum-poker/types";
import type { ImportedEstimation } from "@scrum-poker/utils";

/** Fields a caller may set when creating an estimation. */
export interface CreateEstimationInput {
  name: string;
  description?: string;
}

/** Mutable estimation fields. `isActive` is intentionally excluded — use {@link activateEstimation}. */
export interface UpdateEstimationInput {
  name?: string;
  description?: string | null;
  isEnded?: boolean;
}

/**
 * Create a new estimation in a session. Replaces legacy
 * `ApiService.createNewEstimation` (which generated a uuid and slotted it into
 * the session document); the id is now generated by the DB default.
 */
export async function createEstimation(
  sessionId: string,
  input: CreateEstimationInput,
): Promise<Estimation> {
  const row = await prisma.estimation.create({
    data: {
      sessionId,
      name: input.name,
      description: input.description,
    },
    include: { votes: true },
  });
  return toEstimation(row);
}

/**
 * Patch an estimation's scalar fields (rename / description / end the round).
 * Only provided fields change. This is the non-activation half of the legacy
 * `ApiService.updateEstimation`; activation lives in {@link activateEstimation}
 * to keep the single-active invariant isolated and transactional.
 */
export async function updateEstimation(
  estimationId: string,
  input: UpdateEstimationInput,
): Promise<Estimation> {
  const row = await prisma.estimation.update({
    where: { id: estimationId },
    data: {
      name: input.name,
      description: input.description,
      isEnded: input.isEnded,
    },
    include: { votes: true },
  });
  return toEstimation(row);
}

/**
 * Activate one estimation and deactivate all others in the same session —
 * atomically. This preserves the legacy `updateEstimation` invariant where
 * activating an estimation reduced over the session's estimations setting every
 * other `isActive = false`.
 *
 * Implementation notes:
 * - Runs in a single `$transaction`.
 * - First takes `FOR UPDATE` row locks on **all** of the session's estimations,
 *   ordered by `id`. Acquiring locks in a deterministic order means concurrent
 *   activations of different estimations in the same session serialize cleanly
 *   (no write-skew, no deadlock) and converge to exactly one active estimation.
 * - Then flips every other estimation inactive and the target active.
 *
 * @throws {Error} when the estimation does not exist in the given session.
 */
export async function activateEstimation(
  sessionId: string,
  estimationId: string,
): Promise<Estimation> {
  return prisma.$transaction(async (tx) => {
    // Deterministic lock ordering across the whole session so concurrent
    // activations converge to a single active estimation without deadlocking.
    await tx.$queryRaw`
      SELECT "id" FROM "Estimation"
      WHERE "sessionId" = ${sessionId}
      ORDER BY "id"
      FOR UPDATE
    `;

    await tx.estimation.updateMany({
      where: { sessionId, id: { not: estimationId } },
      data: { isActive: false },
    });

    const { count } = await tx.estimation.updateMany({
      where: { id: estimationId, sessionId },
      data: { isActive: true },
    });

    if (count === 0) {
      throw new Error(
        `Estimation ${estimationId} not found in session ${sessionId}.`,
      );
    }

    const row = await tx.estimation.findUniqueOrThrow({
      where: { id: estimationId },
      include: { votes: true },
    });
    return toEstimation(row);
  });
}

/**
 * Delete an estimation. Cascades to its votes (schema `onDelete: Cascade`).
 * Replaces legacy `ApiService.deleteEstimation`.
 */
export async function deleteEstimation(estimationId: string): Promise<void> {
  await prisma.estimation.delete({ where: { id: estimationId } });
}

/**
 * Bulk-create estimations from parsed CSV rows (see
 * `@scrum-poker/utils` `parseEstimationsCsv`). Replaces legacy
 * `ApiService.importEstimations`, which `Object.assign`-merged a map of new
 * estimations into the session document. Uses `createManyAndReturn` so the
 * created rows (and only those) are returned, ordered by creation.
 *
 * Empty descriptions from the CSV are normalized to `null`.
 */
export async function importEstimations(
  sessionId: string,
  rows: readonly ImportedEstimation[],
): Promise<Estimation[]> {
  if (rows.length === 0) {
    return [];
  }

  const created = await prisma.estimation.createManyAndReturn({
    data: rows.map((row) => ({
      sessionId,
      name: row.name,
      description: row.description ? row.description : null,
    })),
  });

  return created.map((row) => toEstimation(row));
}
